// Generated by Wrangler by running `wrangler types`

interface Env {
	jwt_secret: string;
	CF_INDEX_JOBS: D1Database;
	CF_TRANSCRIPTION_JOBS: D1Database;
	CF_USERS: D1Database;
	CF_YOUTUBE_CLIPS: D1Database;
	CF_TWITCH_CLIPS: D1Database;
}
